# 服务器配置
# 环境变量: SERVER_PORT, SERVER_MODE
server:
  port: "8080"
  mode: "debug"

# 数据库配置
# 环境变量: DATABASE_HOST, DATABASE_PORT, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_DBNAME
database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "memberlink_lite"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  # 连接池配置
  # 环境变量: DATABASE_MAX_IDLE_CONNS, DATABASE_MAX_OPEN_CONNS, DATABASE_CONN_MAX_LIFETIME_HOURS
  max_idle_conns: 10              # 最大空闲连接数
  max_open_conns: 50             # 最大打开连接数
  conn_max_lifetime_hours: 2      # 连接最大生存时间（小时）

# JWT配置
# 环境变量: JWT_SECRET, JWT_ISSUER, JWT_ACCESS_TOKEN_TTL, JWT_REFRESH_TOKEN_TTL
jwt:
  secret: "memberlink-lite-secret-key-change-in-production"
  issuer: "memberlink-lite"
  access_token_ttl: 24    # hours
  refresh_token_ttl: 168  # hours (7 days)

# 日志配置
# 环境变量: LOG_LEVEL, LOG_FORMAT
log:
  level: "info"
  format: "json"

# 存储配置
storage:
  type: "local"  # 存储类型: local
  # 本地存储配置
  local:
    base_path: "./uploads"
    base_url: "http://localhost:8080/uploads/"

# CORS配置
# 环境变量: CORS_ALLOWED_ORIGINS, CORS_ALLOW_CREDENTIALS, CORS_MAX_AGE
cors:
  # 允许的来源域名，逗号分隔，生产环境请配置具体域名
  allowed_origins: "http://localhost:3000,http://localhost:8080"
  allow_credentials: true
  max_age: "12h"