# 博客系统配置文件

server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "matuto_blog"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime_hours: 1

jwt:
  secret: "matuto-blog-secret-key-change-in-production"
  issuer: "matuto-blog"
  access_token_ttl: 24   # 小时
  refresh_token_ttl: 168 # 小时 (7天)

log:
  level: "info"
  format: "json"

storage:
  type: "local"
  local:
    base_path: "./web/uploads"
    base_url: "http://localhost:8080/uploads/"

theme:
  current: "default"
  path: "./web/templates"

cors:
  allowed_origins: "http://localhost:3000,http://localhost:8080"
  allow_credentials: true
  max_age: "12h"